---
title: "Monthly Inflation Writeup"
subtitle: "CPI Data Analysis"
author: 
  - "Mike Konczal"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "80%",
  cache = FALSE,
  echo = FALSE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
library(tidyverse)
library(distill)
library(stargazer)
library(janitor)
library(tidyverse)
library(ggtext)
library(ggrepel)
library(huxtable)
library(scales)
library(lubridate)
library(tidytext)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF",
  extra_css = list(
  ".has-continuation" = list(
  "display" = "block !important"
    )
  )
)
```

```{r start_code, fig.align='center', fig.width = 6, fig.height = 3}
source("/Users/mkonczal/Documents/GitHub/BLS-CPI-Inflation-Analysis/monthly_analysis.R")
```
### Core Inflation

```{r Graphic_1, fig.align='center', fig.height = 4.5}
MI_Graphic1
```
---
### Transitory Inflation

```{r Graphic_2, fig.align='center', fig.height = 4.5}
MI_Graphic2
```
---
### Core Inflation

```{r Graphic_3, fig.align='center', fig.height = 4.5}
MI_Graphic3
```
---
### Decomposition of Services Inflation

```{r Graphic_4, fig.align='center', fig.height = 4.5}
MI_Graphic4
```
---
### Larger Exclusions

```{r Graphic_5, fig.align='center', fig.height = 4.5}
MI_Graphic5
```